# Generated by Django 3.1.7 on 2021-07-26 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210716_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userkind',
            options={'verbose_name': 'Вид деятельности', 'verbose_name_plural': 'Виды деятельности'},
        ),
        migrations.AlterField(
            model_name='user',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.userkind', verbose_name='Вид деятельности'),
        ),
    ]
