# Generated by Django 3.1.7 on 2021-04-04 10:28

from django.db import migrations, models
import django.db.models.deletion
import mypatients.models


class Migration(migrations.Migration):

    dependencies = [
        ('mypatients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.PositiveSmallIntegerField(verbose_name='Номер палаты')),
                ('diagnosis', models.TextField(verbose_name='Краткий диагноз')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Время поступления')),
                ('record', models.FileField(upload_to=mypatients.models.record_file_name, verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'История болезни',
                'verbose_name_plural': 'Истории болезней',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('login', models.CharField(max_length=20, verbose_name='Логин')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Вид обследования')),
                ('date_1', models.DateField(auto_now_add=True, verbose_name='Дата назначения')),
                ('date_2', models.DateField(auto_now=True, verbose_name='Дата исполнения')),
                ('result', models.FileField(upload_to=mypatients.models.examination_file_name, verbose_name='Результат')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypatients.clinicalrecord', verbose_name='История болезни')),
            ],
            options={
                'verbose_name': 'Обследование',
                'verbose_name_plural': 'Обследования',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Уведомление')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypatients.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назначение')),
                ('date_1', models.DateField(verbose_name='Дата начала приема')),
                ('date_2', models.DateField(verbose_name='Дата окончания приема')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypatients.clinicalrecord', verbose_name='История болезни')),
            ],
            options={
                'verbose_name': 'Назначение',
                'verbose_name_plural': 'Назначения',
            },
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Время замера')),
                ('puls', models.PositiveSmallIntegerField(verbose_name='Пульс')),
                ('pressure', models.CharField(max_length=7, verbose_name='Двление')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypatients.clinicalrecord', verbose_name='История болезни')),
            ],
            options={
                'verbose_name': 'Давление и пульс',
                'verbose_name_plural': 'Значения давления и пульса',
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Время замера')),
                ('value', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Значение')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypatients.clinicalrecord', verbose_name='История болезни')),
            ],
            options={
                'verbose_name': 'Температура',
                'verbose_name_plural': 'Температуры',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mypatients.doctor', verbose_name='Врач'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mypatients.patient', verbose_name='Пациент'),
        ),
    ]
