# Generated by Django 3.1.7 on 2021-07-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypatients', '0002_auto_20210716_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='date_1',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='date_2',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата исполнения'),
        ),
    ]
