# Generated by Django 3.1.7 on 2021-05-18 12:59

from django.db import migrations, models
import mypatients.models


class Migration(migrations.Migration):

    dependencies = [
        ('mypatients', '0002_auto_20210404_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='result',
            field=models.FileField(blank=True, upload_to=mypatients.models.examination_file_name, verbose_name='Результат'),
        ),
    ]
