# Generated by Django 3.1.7 on 2021-05-24 14:36

import ckeditor.fields
from django.db import migrations, models
import mypatients.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mypatients', '0002_auto_20210520_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='allergic_history',
            field=ckeditor.fields.RichTextField(blank=True, default='не отягощен.', null=True, verbose_name='Аллергический анамнез'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='anamnesis',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Anamnesis morbi'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='blood_transfusion',
            field=ckeditor.fields.RichTextField(blank=True, default='не проводились.', null=True, verbose_name='Гемотрансфузии'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='complaint',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Жалобы при поступлении'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='epidanamnesis',
            field=ckeditor.fields.RichTextField(blank=True, default='за границы Самарской области последние 14 дней не выезжал(а), контакт с лихорадящими больными отрицает.', null=True, verbose_name='Эпиданамнез'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='expert_history',
            field=ckeditor.fields.RichTextField(blank=True, default='в л/н не нуждается.', null=True, verbose_name='Экспертный анамнез'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='habitual_intoxication',
            field=ckeditor.fields.RichTextField(blank=True, default='отрицает.', null=True, verbose_name='Привычные интоксикации'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='occupational_hazards',
            field=ckeditor.fields.RichTextField(blank=True, default='отрицает.', null=True, verbose_name='Профессиональные опасности'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='past_illnesses',
            field=ckeditor.fields.RichTextField(blank=True, default='вирусный гепатит отриц., туберкулез отриц., ВИЧ отриц., сахарный диабет отриц.', null=True, verbose_name='Перенесенные заболевания'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='respiratory_system',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Органы дыхания'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='status_p_c',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Status praesens communis'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='clinicalrecord',
            name='record',
            field=models.FileField(blank=True, null=True, upload_to=mypatients.models.record_file_name, verbose_name='Файл'),
        ),
    ]
