# Generated by Django 3.1.7 on 2021-05-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypatients', '0003_auto_20210518_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='date_1',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='date_2',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата исполнения'),
        ),
    ]
