# Generated by Django 3.1.7 on 2021-05-25 12:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypatients', '0003_auto_20210524_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='circulatory_organs',
            field=ckeditor.fields.RichTextField(blank=True, default='При осмотре области сердца без особенностей. Границы относительной сердечной тупости: расширены влево. Аускультация сердца тоны сердца приглушены, ритм правильный. Исследование артерий: Пульс 70 ударов в 1 мин, удовлетворительных свойств. Артериальное давление : на правой руке 120 и 80 мм рт. ст,на левой руке 120 и 80 мм рт. ст.', null=True, verbose_name='Органы кровообращения'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='data_from_additional_research_methods',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Данные дополнительных методов исследования'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='digestive_organs',
            field=ckeditor.fields.RichTextField(blank=True, default='Язык чистый, влажный. Живот имеет округлую конфигурацию. Свободной жидкости нет. Болезненности нет. Стул был накануне оформленный. Печень у края рёберной дуги. Желчный пузырь не пальпируется. Селезенка не пальпируется.', null=True, verbose_name='Органы пищеварения'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='preliminary_diagnosis',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Предварительный диагноз'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='primary_diagnosis',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Основной диагноз'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='status_localis',
            field=ckeditor.fields.RichTextField(blank=True, default='Менингеальных знаков нет. Зрачки  D=S. Фотореакция живая, содружественная. Глазные щели D=S. Нистагма нет. Движения глазных яблок в полном объеме. Лицо симметрично. Язык по средней линии. Сила во всех группах мышц 5 баллов. Сухожильные рефлексы с рук и ног D=S. Патологических знаков нет. Чувствительных нарушений не выявленно. Симптомы натяжения отрицательные. В позе Ромберга - устойчив. Кординаторные пробы выполняет уверенно с двух сторон. Походка не нарушена.', null=True, verbose_name='Status localis'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='urinary_organs',
            field=ckeditor.fields.RichTextField(blank=True, default='Почечная область при осмотре без особенностей. Симптом Пастернацкого отрицательный с двух сторон. Диурез достаточный.', null=True, verbose_name='Органы мочевыделения'),
        ),
        migrations.AlterField(
            model_name='clinicalrecord',
            name='occupational_hazards',
            field=ckeditor.fields.RichTextField(blank=True, default='отрицает.', null=True, verbose_name='Профессиональные вредности'),
        ),
        migrations.AlterField(
            model_name='clinicalrecord',
            name='respiratory_system',
            field=ckeditor.fields.RichTextField(blank=True, default='Голос обычный. Форма грудной клетки цилиндрическая. Асимметрии грудной клетки нет. Число дыханий в 1 мин. 17. Одышки нет. Перкуторно лёгочный тон. Аускультативно везикулярное дыхание.', null=True, verbose_name='Органы дыхания'),
        ),
        migrations.AlterField(
            model_name='clinicalrecord',
            name='status_p_c',
            field=ckeditor.fields.RichTextField(blank=True, default='общее состояние средней степени тяжести. Положение активное. Сознание ясное. Телосложение правильное. Кожные покровы бледно-розовые. Слизистые чистые. Отёков нет. Варикозное расширение подкожных вен - нет. Подкожно-жировой слой развит умеренно. Лимфатические узлы не увеличены, безболезненные.', null=True, verbose_name='Status praesens communis'),
        ),
    ]
