# Generated by Django 3.1.7 on 2021-05-25 23:31

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypatients', '0004_auto_20210525_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рост'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='clinicalrecord',
            name='status_localis',
            field=ckeditor.fields.RichTextField(blank=True, default='Менингеальных знаков нет. Зрачки D=S. Фотореакция живая, содружественная. Глазные щели D=S. Нистагма нет. Движения глазных яблок в полном объеме. Лицо симметрично. Язык по средней линии. Сила во всех группах мышц 5 баллов. Сухожильные рефлексы с рук и ног D=S. Патологических знаков нет. Чувствительных нарушений не выявленно. Симптомы натяжения отрицательные. В позе Ромберга - устойчив. Кординаторные пробы выполняет уверенно с двух сторон. Походка не нарушена.', null=True, verbose_name='Status localis'),
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2021, 5, 25, 23, 31, 40, 466961), verbose_name='Время')),
                ('complaint', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Жалобы на')),
                ('status_p_c', ckeditor.fields.RichTextField(blank=True, default='общее состояние средней степени тяжести. Положение активное. Сознание ясное. Телосложение правильное. Кожные покровы бледно-розовые. Слизистые чистые. Отёков нет. Варикозное расширение подкожных вен - нет. Подкожно-жировой слой развит умеренно. Лимфатические узлы не увеличены, безболезненные.', null=True, verbose_name='Объективный статус')),
                ('status_localis', ckeditor.fields.RichTextField(blank=True, default='В сознании, оглушение (легкое), сопор, кома . Адекватен. Снижение критики, памяти, внимания. Фон настроения. ЧМН: Зрачки округлой формы D=S. Лицо : симметричное, центральный, периферический парез VII п. справа, слева. Гипомимия. SNy - нет,установочный,среднеразмашистый, затухающий вправо, влево. Горизонтальный, вертикальный, при взгладе прямо, в крайних отведениях. Язык - по средней линии, отклоняется вправо, влево. Чувствительность: - сохранена - гемигипестезия - справа, слева. Тонус: не изменен; повышен - по пирамидному D S- по э\\пирамидному D S Сила: силовой разницы нет: D=S= баллов , парез справа / слева баллов в руке, баллов ноге. Походка: не изменена, не может ходить, атактическая,покачивается, гемипаретическая, олигобрадикинезия. В п. Ромберга устойчив , покачивается, не стоит. КП – выполняет удовлетворительно, нечетко - справа , слева, с 2-х сторон. Сухожильный рефлексы: живые,торпидные, с рук D S,с ног D S. (+) с-м Бабинского (+) с-м хоботка. ', null=True, verbose_name='Неврологический статус')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypatients.clinicalrecord', verbose_name='История болезни')),
            ],
            options={
                'verbose_name': 'Дневник',
                'verbose_name_plural': 'Дневники',
            },
        ),
    ]
