# Generated by Django 3.1.7 on 2021-05-25 23:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mypatients', '0005_auto_20210525_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 23, 34, 20, 547187, tzinfo=utc), verbose_name='Время'),
        ),
    ]
