# Generated by Django 3.1.7 on 2021-05-25 23:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mypatients', '0006_auto_20210525_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время'),
        ),
    ]
