# Generated by Django 3.1.7 on 2021-05-26 21:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypatients', '0007_auto_20210525_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='recommendation',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Рекомендации'),
        ),
    ]
