# Generated by Django 3.1.7 on 2021-05-29 15:19

from django.db import migrations, models
import mypatients.models


class Migration(migrations.Migration):

    dependencies = [
        ('mypatients', '0009_patient_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='discharge',
            field=models.FileField(blank=True, null=True, upload_to=mypatients.models.record_file_name, verbose_name='Выписка'),
        ),
        migrations.AlterField(
            model_name='clinicalrecord',
            name='record',
            field=models.FileField(blank=True, null=True, upload_to=mypatients.models.record_file_name, verbose_name='История'),
        ),
    ]
