# Generated by Django 3.1.7 on 2021-06-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypatients', '0010_auto_20210529_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='height',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='weight',
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рост'),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вес'),
        ),
    ]
